definitions:
  wb-test_pkg_utils_http-utils.ErrorDetail:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  wb-test_pkg_utils_http-utils.ErrorResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/wb-test_pkg_utils_http-utils.ErrorDetail'
        type: array
      log_timestamp:
        type: string
      message:
        type: string
      request_id:
        type: string
      status:
        type: integer
    type: object
  wb-test_pkg_utils_http-utils.Status:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  description: Документация сервиса заказа
  title: WB Test
  version: "1.0"
paths:
  /live:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/wb-test_pkg_utils_http-utils.Status'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/wb-test_pkg_utils_http-utils.ErrorResponse'
      summary: Health check
      tags:
      - Health
swagger: "2.0"
